### ISSUE TITLE
.bind loaded Method 

### ISSUE THREAD

**Issue by WazzaJB** [StanScates/Tweet.js-Mod#10]
Hi there,

I have just moved a site from the original seaofclouds Tweet.js to yours, I'm really impressed with how easy it was to move.

I'm having an issue with the loaded firing before the tweets are added?

Thanks,
Warren

**Comment by dekortage** [comment]
I'm in the same situation. I migrated to your mod of Tweet.js and it was really easy to do -- but nothing fires even with .bind("loaded") in place.  Even something as simple as this does not work:

.bind("loaded",function(){ window.alert('loaded'); });

**Comment by wtadesign** [comment]
please have a look at 

https://github.com/StanScates/Tweet.js-Mod/issues/8#issuecomment-19358704

to see if these solutions can help.

**Comment by joshmoto** [comment]
Can anyone help please the bind loaded method does not work anymore? This is very sad for me. Does anyone have a fix?

**Comment by eponym** [comment]
I did a quick mod to mine, but haven't forked/requested a pull.

In the options object (var s), add a:

```
callback: null
```

somewhere. Don't forget to add the comma before or after it, depending on where you put it.

Then add this the end of the success function for the ajax call:

```
if(s.callback) { s.callback(); }
```

After that you can add another init option when you call the plugin:

```
$("#twitter").tweet({
    username: "mytwittername",
    count: 3,
    loading_text: "loading tweets…",
    callback: function(){
        //callback code goes here
    }
});
```

**Comment by joshmoto** [comment]
@eponym dude this is genius thank you so much!!!
