### ISSUE TITLE
Another 'Loading Tweets' issue

### ISSUE THREAD

**Issue by welookwelike** [StanScates/Tweet.js-Mod#32]
![screen shot 2013-07-18 at 17 38 29](https://f.cloud.github.com/assets/5040813/820604/83363dee-efc8-11e2-82d2-238c89b49014.png)
Hi

Kind of puling my hair out also with my Wordpress site.

So I've downloaded the files, amended index.php with my unique tokens etc and uploaded everything to the server and it just shows 'Loading Tweets' and nothing else - http://www.welookwelike.com/design-services/

Here's the JS in my header.php file..

<script type='text/javascript'>
    jQuery(function($){
        $(".tweet").tweet({
            username: "WeLookWeLIke",
            join_text: "auto",
            count: 1,
            auto_join_text_default: "I said,", 
            auto_join_text_ed: "I",
            auto_join_text_ing: "I was",
            auto_join_text_reply: "I replied to",
            auto_join_text_url: "I was checking out",
            loading_text: "loading tweets..."
        });
    });
</script>

NOTE: My twitter folder is in the server root i.e. outside of the Wordpress theme - should it be moved inside and I change the modpath to something along the lines of ./wp_content/themes/ ...

Any help would be appreciated - not sure what else to try.

Ta

**Comment by paultibbetts** [comment]
You've still got the original tweet script below the new one which ( _I think_ ) will be replacing the tweet() function, which is doing a GET to the old Twitter API and throwing an error.

Try removing the second reference to the script ( down in the footer ) and it should work.

The script by default has a modpath of _root/twitter/_ so that should be fine, but if you wanted to move it into the theme you could do:

_Twitter folder would be at wp-content/themes/WeLookWeLike/inc/twitter_

``` javascript
<script type="text/javascript" charset="utf-8" src="<?php echo get_template_directory_uri();?>/inc/twitter/jquery.tweet.js"></script>
<?php $modpath = get_template_directory_uri() . '/inc/twitter/';?>
<script type='text/javascript'>
    jQuery(function($){
        $(".tweet").tweet({
            modpath: '<?php echo $modpath;?>',
            username: "WeLookWeLIke",
            join_text: "auto",
            count: 1,
            auto_join_text_default: "I said,", 
            auto_join_text_ed: "I",
            auto_join_text_ing: "I was",
            auto_join_text_reply: "I replied to",
            auto_join_text_url: "I was checking out",
            loading_text: "loading tweets..."
        });
    });
</script>
```

**Comment by welookwelike** [comment]
LEGEND! Thank you so much :)
