### ISSUE TITLE
No error but no tweets (no 'loading' message)

### ISSUE THREAD

**Issue by tokola** [StanScates/Tweet.js-Mod#33]
Hi Stan,

I have eventually managed to apply the mod and get everything working. However the tweets list appears empty. While debugging I can see the JSON file which is delivered correctly from Twitter. It is also cached to disk on my local copy (using wamp, since the server one is not writable). No error appears to occur while checking with firebug.

Could you please have a look at the website and tell me what might be wrong? I've also contacted Steve and he directed me to you since, he said, you have changed the javascript code.
http://www.hci.vt.edu/

Thanks a lot!

**Comment by svondervoort** [comment]
I'm having the same problem at the moment.
If I have more news about this I'll update it in this thread to keep the issues minimum.

**Comment by paultibbetts** [comment]
@tokola I've just been on your site and it's giving me these two errors:

![image](https://f.cloud.github.com/assets/2053583/835609/378bc6ec-f2df-11e2-9dfb-b5930da85692.png)

Try changing your permissions on the cache directory/twitter folder - my Twitter folder is 755 and is working.

**Comment by tokola** [comment]
Thanks, but as I said in my original e-mail I am having the same problem on my local copy too, where there is no issue of write access (I can actually see the cached json file). I just didn't bother to deactivate caching on the server copy, since I know the administrator (not me, unfortunately) prefers not to provide write-access. Caching shouldn't prevent the tweets from being displayed, right Stan?

**Comment by tokola** [comment]
Stan,
any updates on this? I really need to re-activate the tweets on the website. Is it something you plan to fix soon (within the next few days) or it might take longer?

Thanks again for your support.

**Comment by svondervoort** [comment]
The problem I'm having is that in the console I can see the POST being done and answered by twitter. It even writes the cached JSON, but it looks like the script never reads the JSON afterwards.

**Comment by tokola** [comment]
That's exactly what's happening on my end. It seems authentication and everything on the Twitter side works fine.

**Comment by StanScates** [comment]
This is odd. I advise you ensure your markup is correct, see if it works after removing all other unnecessary scripts from the page, etc. Obviously something is interfering with the DOM preventing the script from working as it should

**Comment by tokola** [comment]
Stan,
you were right. It seems that some of the changes you made rendered it incompatible with the MooTools framework, and specifically the core component (tweets appear fine once deactivated).  Do you have any idea what might be causing the conflict? What was the thing you changed and might be causing this behavior? (tweets not appearing at all inside a grid)

It would be extremely helpful if you gave me some guidance, since I am not experienced in javascript and have trouble figuring this out. The site is: http://www.hci.vt.edu/
Thanks!

**Comment by svondervoort** [comment]
I also disabled Mootools and that did the trick. Thanks Tokola and Stan!
