### ISSUE TITLE
Tweets not loading since Wordpress update to 3.5.2

### ISSUE THREAD

**Issue by skitson** [StanScates/Tweet.js-Mod#36]
Hi Stan

My Tweets don't seem to be loading anymore since I updated Wordpress to the current version 3.5.2. I moved the call for tweet to the window load function but it's still not pulling in. I get the following error in the console:

Uncaught TypeError: Cannot read property 'statuses' of null

Just wondered if you had any idea what might be causing it?

Many thanks

**Comment by skitson** [comment]
Seems to be working now? http://www.samkitson.co.uk/

Thanks for writing such a handy script!

**Comment by rebz** [comment]
Was there anything in particular you had to do? I've been having this same issue for a couple weeks now.

**Comment by skitson** [comment]
I ended up calling the script on window load rather than on document ready. That's the only thing I changed.

```
$(window).load(function(){
    // initialise Tweet plugin
});
```

Try doing that then clear your cache.
