### ISSUE TITLE
Tweets load, but never show up in the source code!

### ISSUE THREAD

**Issue by jkupczak** [StanScates/Tweet.js-Mod#37]
I'm scratching my head on this one.

Here's an isolated page with Tweet.js: http://hypedance.co/blah.php

You'll see a bunch of tweets show up on your screen in Google Chrome. But if you inspect the page you won't find any of them in there. Just the "loading..." text.

Load the same page in Firefox and you don't see any tweets. But if you refresh often enough, you'll see all the same tweets from Chrome for a nanosecond.

I'm not getting any javascript errors. 

What in the heck is going on?

**Comment by StanScates** [comment]
Without really looking at your code, it's immediately obvious that you are instantiating the plugin in some sort of recursive loop or function, which is causing your issues.

http://cl.ly/image/420Y3e292R2K
