### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by MadMonkInteractive** [StanScates/Tweet.js-Mod#38]
Everything is in the "normal" place but whenever the script runs I get this error:

`Cannot read property 'length' of null  ...  jquery.tweet.js:179`

Debug is set to  `True` and cache set to `False`. I've tried switching from relative to static links for my `/lib/` folder but no matter what I get the same error.

I am testing this with a Twitter app key that is fairly old, if that has anything to do with the matter.

EDIT: Found the issue in the script call.

**Comment by lspoor** [comment]
Care to share how you fixed it? I'm getting the same error..
