### ISSUE TITLE
Error Code #34

### ISSUE THREAD

**Issue by 350d** [StanScates/Tweet.js-Mod#4]
Morning!
I have an error "Twitter Error: "Sorry, that page does not exist", Error Code #34"
Application created, all keys/secrets filled up, but i'm still receiving this error in php/js console. Debug is "true". How to debug/fix this issue?
Thank you.

**Comment by StanScates** [comment]
Hey @350d,
Could you possibly [email](mailto:sc8ssb@gmail.com) me a link to the page this is being run on so I can take a look at it? It would be a great help in troubleshooting. If you can't do that for whatever reason, we can go from there.
Thanks

**Comment by 350d** [comment]
Sorry! Client just DELETED the twitter account - that was an issue!

**Comment by StanScates** [comment]
Ah. Glad you got that sorted out :)
Feel free to let me know if you have any other problems
