### ISSUE TITLE
X-Domain

### ISSUE THREAD

**Issue by rickydazla** [StanScates/Tweet.js-Mod#9]
If I am embedding tweets on a site (e.g. hosted eComm) will your solution work if the scripts etc are hosted at a diff domain - e.g. CDN for the eComm site in question or personal server?

**Comment by wtadesign** [comment]
Have you tried :

The twitter folder needs to be in the root directory of server/domain your Twitter feed page is on, so you would need to access the ftp of the eComm site, upload the "twitter" folder to that sever. Set up the "Your Twitter App" url as the "eComm site" domain url.

**Comment by rickydazla** [comment]
I have not tried. Figured I would ask first. Site domain is e.g. store.ecomm.com BUT assets are served from cdn.com ...

**Comment by wtadesign** [comment]
if it does not work for you, you could try just setting up a "twitter" folder on a server you have access to abc.com,  Set up the "Your Twitter App" url for that same domain abc.com, create a single page for just the twitter feed on that server abc.com.  On your ecomm site iframe or php include that twitter page you set up.

**Comment by StanScates** [comment]
[https://github.com/StanScates/Tweet.js-Mod/issues/6](https://github.com/StanScates/Tweet.js-Mod/issues/6)

**Comment by jasonabird** [comment]
Created a jsonp fork with some checks for Access-Control-Allow-Origin here https://github.com/jasonabird/Tweet.js-Mod.

**Comment by rickydazla** [comment]
Jason! Thanks. Got it working on Shopify :8ball:
